services:
  pulumi: &pulumi
    image: pulumi 
    user: appuser
    build:
      context: ./dockerfiles
      args:
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
      dockerfile: Dockerfile.agent
    hostname: pulumi 
    container_name: pulumi
    working_dir: /app 
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/app/scripts

    networks:
      - kind
  
  app: &app
    image: python-app
    user: appuser
    build:
      context: ./dockerfiles
      args:
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
      dockerfile: Dockerfile.app
    hostname: python-app
    container_name: python-app
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./application_files:/app
    networks:
      - kind

networks:
  kind:
    name: kind