apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: python-app
  name: python-app
  namespace: kafka
spec:
  containers:
  - image: python-app
    name: python-app
    resources: {}
    imagePullPolicy: Never
    command: ["sleep", "100000"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
