apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: orders
  labels:
    strimzi.io/cluster: systems-kafka-cluster
spec:
  partitions: 3
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: fulfillment
  labels:
    strimzi.io/cluster: systems-kafka-cluster
spec:
  partitions: 3
  replicas: 2